### ISSUE TITLE
Unexpected behavior when fetch data with $or

### ISSUE THREAD

**Issue by Brianaldo** [turnkey-devs/utils-ts#40]
**mikro-orm**
https://github.com/turnkey-devs/utils-ts/blob/dev/src/utils/database/mikro-orm/__tests__/mikroorm_database.common.spec.ts#L833-L866

**typeorm**
https://github.com/turnkey-devs/utils-ts/blob/dev/src/utils/database/typeorm/__tests__/typeorm_database.common.spec.ts#L852-L885

**Comment by fatihaziz** [comment]
solved
