### ISSUE TITLE
Cannot fetch data using dataloader

### ISSUE THREAD

**Issue by Brianaldo** [turnkey-devs/utils-ts#41]
**mikro-orm**
https://github.com/turnkey-devs/utils-ts/blob/dev/src/utils/database/mikro-orm/__tests__/mikroorm_database.common.spec.ts#L869-L901

**typeorm**
https://github.com/turnkey-devs/utils-ts/blob/dev/src/utils/database/typeorm/__tests__/typeorm_database.common.spec.ts#L888-L920

**Comment by fatihaziz** [comment]
solved
