### ISSUE TITLE
Cannot fetch data when empty object

### ISSUE THREAD

**Issue by Brianaldo** [turnkey-devs/utils-ts#42]
**mikro-orm**
https://github.com/turnkey-devs/utils-ts/blob/dev/src/utils/database/mikro-orm/__tests__/mikroorm_database.common.spec.ts#L904-L941

**typeorm**
https://github.com/turnkey-devs/utils-ts/blob/dev/src/utils/database/typeorm/__tests__/typeorm_database.common.spec.ts#L923-L960

**Comment by fatihaziz** [comment]
solved
